---
ansible_connection: network_cli
ansible_network_os: nxos
#
provider_ssh:
  host: "{{ ansible_host }}"
  username: "{{ ansible_username }}"
  password: "{{ ansible_password }}"
  transport: network_cli
#
