---
# Create the boot LUNs for Servers for iSCSI configuration
- name: Create the boot LUNs for Servers for iSCSI config
  netapp.ontap.na_ontap_lun:
    state: present
    vserver: "{{svm_specs.svm_name}}"
    name: "{{item.hostname}}-ISCSI"
    size: "{{svm_specs.boot_luns_iscsi.size}}"
    flexvol_name: "{{svm_specs.boot_luns_iscsi.residing_vol}}"
    ostype: "{{svm_specs.os_type}}"
    space_reserve: false
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{iscsi_esxi_hosts}}"
  when: "('iscsi' in svm_specs.allowed_protocols)"
  tags:
    - ontap_lun_create_iscsi

# Create the boot LUNs for Servers for FCP configuration
- name: Create the boot LUNs for Servers for FC config
  netapp.ontap.na_ontap_lun:
    state: present
    vserver: "{{svm_specs.svm_name}}"
    name: "{{item.hostname}}-FCP"
    size: "{{svm_specs.boot_luns_fcp.size}}"
    flexvol_name: "{{svm_specs.boot_luns_fcp.residing_vol}}"
    ostype: "{{svm_specs.os_type}}"
    space_reserve: false
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{fc_esxi_hosts}}"
  when: "('fcp' in svm_specs.allowed_protocols)"
  tags:
    - ontap_lun_create_fcp

# Create igroups for iSCSI
- name: Create the igroups for iSCSI
  netapp.ontap.na_ontap_igroup:
    state: present
    vserver: "{{svm_specs.svm_name}}"
    initiator: "{{item.iscsi_iqn}}"
    ostype: "{{svm_specs.os_type}}"
    initiator_group_type: iscsi
    name: "{{item.hostname}}-ISCSI"
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{iscsi_esxi_hosts}}"
  when: "('iscsi' in svm_specs.allowed_protocols)"
  tags:
    - ontap_iscsi_igroup_create

# Getting the FCP igroup names with their corresponding WWPNs
- name: Get the FCP igroup names with their corresponding WWPNs
  ansible.builtin.set_fact:
    fcp_igroup_wwpn_list: "{{ fcp_igroup_wwpn_list|default([]) + [ {'igroup_name': item.hostname, 'wwpns': [item.fcp_a_wwpn,item.fcp_b_wwpn]} ] }}"
  with_items:
    - "{{fc_esxi_hosts}}"
  when:
    - "('fcp' in svm_specs.allowed_protocols)"
  tags:
    - ontap_fcp_igroup_create

# Create igroups for FCP
# For FCP, we need to add multiple WWPNs from the single host to an igroup
- name: Create the igroups for FCP
  netapp.ontap.na_ontap_igroup:
    state: present
    vserver: "{{svm_specs.svm_name}}"
    initiators: "{{item.wwpns}}"
    ostype: "{{svm_specs.os_type}}"
    initiator_group_type: fcp
    name: "{{item.igroup_name}}-FCP"
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{fcp_igroup_wwpn_list}}"
  when: "('fcp' in svm_specs.allowed_protocols)"
  tags:
    - ontap_fcp_igroup_create

# Map the LUNs to iSCSI igroups
- name: Mapping LUN to iSCSI igroup
  netapp.ontap.na_ontap_lun_map:
    state: present
    vserver: "{{svm_specs.svm_name}}"
    initiator_group_name: "{{item.hostname}}-ISCSI"
    path: /vol/{{svm_specs.boot_luns_iscsi.residing_vol}}/{{item.hostname}}-ISCSI
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{iscsi_esxi_hosts}}"
  when: "('iscsi' in svm_specs.allowed_protocols)"
  tags:
    - ontap_map_lun_to_igroup_iscsi

# Map the LUNs to FCP igroups
- name: Mapping LUN to FCP igroup
  netapp.ontap.na_ontap_lun_map:
    state: present
    vserver: "{{svm_specs.svm_name}}"
    initiator_group_name: "{{item.hostname}}-FCP"
    path: /vol/{{svm_specs.boot_luns_iscsi.residing_vol}}/{{item.hostname}}-FCP
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{fc_esxi_hosts}}"
  when: "('fcp' in svm_specs.allowed_protocols)"
  tags:
    - ontap_map_lun_to_igroup_fcp
