---
#
# All the NFS datastores defined in ESXihosts/defaults/main.yml
# are added to all the ESXi hosts. configure_nfs variable must be present
# for the NFS datastore mount
#
  - name: Import esxi_datastores role to get NFS and swap datastores related info
    import_role:
      name: ONTAP/esxi_datastores

  - name: Add NFS datastore to each host
    community.vmware.vmware_host_datastore:
      hostname: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_ssh_pass }}'
      esxi_hostname: '{{ inventory_hostname }}'
      datastore_name: '{{ item.datastore_name }}'
      datastore_type: '{{ nfs_datastore_type }}'
      nfs_server: '{{ item.nfs_lif_ip }}'
      nfs_path: '/{{ item.datastore_name }}'
      validate_certs: no
      state: present
    delegate_to: localhost
    with_items:
      - "{{ nfs_ds_lif_map }}"
    when: configure_nfs == 'true'

# Add swap datastore to ESXi host
  - name: Add swap datastore to ESXi host
    community.vmware.vmware_host_datastore:
      hostname: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_ssh_pass }}'
      esxi_hostname: '{{ inventory_hostname }}'
      datastore_name: '{{ item.datastore_name }}'
      datastore_type: '{{ nfs_datastore_type }}'
      nfs_server: '{{ item.nfs_lif_ip }}'
      nfs_path: '/{{ item.datastore_name }}'
      validate_certs: no
      state: present
    delegate_to: localhost
    with_items:
      - "{{ swap_ds_lif_map }}"
    when: configure_nfs == 'true'

# Add vCLS datastore to ESXi host
  - name: Add vCLS datastore to ESXi host
    community.vmware.vmware_host_datastore:
      hostname: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ ansible_ssh_pass }}'
      esxi_hostname: '{{ inventory_hostname }}'
      datastore_name: '{{ item.datastore_name }}'
      datastore_type: '{{ nfs_datastore_type }}'
      nfs_server: '{{ item.nfs_lif_ip }}'
      nfs_path: '/{{ item.datastore_name }}'
      validate_certs: false
      state: present
    delegate_to: localhost
    with_items:
      - "{{ vcls_ds_lif_map }}"
    when: configure_nfs == 'true'
