---
  # This Task Configures 1 or more NTP Servers in UCSM
  # Configure DNS Servers
  #
  - name: Configure NTP server 1 - Nexus Switch A mgmt0
    cisco.ucs.ucs_ntp_server:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ntp_server: "{{ ntp_servers[0].ip_address }}"
      state: present
    when: ntp_servers is defined
#
  - name: Configure NTP server 2 - Nexus Switch B mgmt0
    cisco.ucs.ucs_ntp_server:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      ntp_server: "{{ ntp_servers[1].ip_address }}"
      state: present
    when: ntp_servers is defined
